name: Destroy My Treehouse
on:
  workflow_dispatch:  # Run manually from GitHub Actions
jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::566702742140:role/GitHubActionsRole
        role-session-name: github-treehouse-session
    - run: terraform init
    - run: terraform destroy -auto-approve